def stuff():
  try foo():
    result:
      result
  catch:
    error.e:
      #('error, error, e)
